-- Saneamientos Pereda — MySQL schema (migrated from Supabase Postgres)
-- UUIDs kept as CHAR(36) so existing IDs survive the migration unchanged.

CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  collection TEXT NOT NULL,
  variant TEXT,
  image_url TEXT NOT NULL,
  secondary_image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  description TEXT,
  price DECIMAL(10,2),
  available TINYINT(1) NOT NULL DEFAULT 1,
  sold TINYINT(1) NOT NULL DEFAULT 0,
  color TEXT,
  size INT,
  product_type VARCHAR(64) NOT NULL DEFAULT 'bano',
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS product_photos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  image_url TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_photos FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS brands (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT NOT NULL,
  category VARCHAR(64) DEFAULT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ambientes (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  cover_image_url TEXT NOT NULL,
  specs JSON NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ambiente_photos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  ambiente_id CHAR(36) NOT NULL,
  image_url TEXT NOT NULL,
  caption TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ambiente_photos FOREIGN KEY (ambiente_id) REFERENCES ambientes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tiendas (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  postal_code VARCHAR(16) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  hours_tienda TEXT NOT NULL,
  hours_fontaneria TEXT NOT NULL,
  hours_sabados TEXT NOT NULL,
  hours_verano TEXT NOT NULL,
  emails JSON NOT NULL,
  cover_image_url TEXT,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tienda_photos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tienda_id CHAR(36) NOT NULL,
  image_url TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tienda_photos FOREIGN KEY (tienda_id) REFERENCES tiendas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_settings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  `key` VARCHAR(191) NOT NULL UNIQUE,
  value TEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS denuncias (
  id CHAR(36) NOT NULL PRIMARY KEY,
  pin VARCHAR(32) NOT NULL UNIQUE,
  hechos TEXT NOT NULL,
  seccion_lugar TEXT NOT NULL,
  vinculacion TEXT NOT NULL,
  personas_involucradas TEXT NOT NULL,
  momento TEXT NOT NULL,
  documentos_info TEXT NOT NULL,
  estado VARCHAR(32) NOT NULL DEFAULT 'pendiente',
  respuesta TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS job_applications (
  id CHAR(36) NOT NULL PRIMARY KEY,
  nombre TEXT NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefono VARCHAR(32) NOT NULL DEFAULT '',
  mensaje TEXT,
  cv_url TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS presupuesto_requests (
  id CHAR(36) NOT NULL PRIMARY KEY,
  nombre TEXT NOT NULL,
  localidad TEXT NOT NULL,
  email VARCHAR(255) NOT NULL,
  asunto TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cliente_requests (
  id CHAR(36) NOT NULL PRIMARY KEY,
  nombre TEXT NOT NULL,
  empresa TEXT NOT NULL,
  cif VARCHAR(32) NOT NULL DEFAULT '',
  localidad TEXT NOT NULL,
  telefono VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL,
  actividad TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
